[%
TOKENS = {
  "already_paid" = "This payment has already been processed and paid."
  "contact_librarian" = "Please contact a librarian for details."
  "error_occurred" = "Something went wrong - payment failed"
  "error_occurred_contact_library" = ". Please contact the library."
  "home_breadcrumb" = "Home"
  "no_amount" = "No amount was passed in!"
  "order_id" = "Order ID"
  "payment_cancelled" = "Your payment was cancelled."
  "payment_process_success" = " has been processed successfully!"
  "payment_result_breadcrumb" = "Payment Results"
  "redirect" = "Redirecting to Swedbank Pay..."
  "redirect_click_label" = "If you are not redirected in 10 seconds,"
  "redirect_click_link" = "click here"
  "return_to_your_charges" = "Return to <a href=\"/cgi-bin/koha/opac-account.pl\">your charges</a>."
  "transaction_not_found" = "Transaction not found."
  "unknown_error" = "Unknown error."
  "your_payment_breadcrumb" = "Your Payment"
  "your_payment_of" = "Your payment of "
}
%]
