[%
TOKENS = {
  "already_paid" = "Tämä maksu on jo käsitelty ja maksettu."
  "contact_librarian" = "Ota yhteyttä kirjastoosi."
  "error_occurred" = "Virhe - maksu epäonnistui"
  "error_occurred_contact_library" = ". Ota yhteyttä kirjastoosi."
  "home_breadcrumb" = "Etusivu"
  "no_amount" = "Tuntematon maksun määrä!"
  "order_id" = "Tilaustunniste"
  "payment_cancelled" = "Maksusi on peruttu."
  "payment_process_success" = " on käsitelty onnistuneesti!"
  "payment_result_breadcrumb" = "Maksun tila"
  "redirect" = "Uudelleenohjataan Swedbank Pay -maksuliittymään..."
  "redirect_click_label" = "Jos selaimesi ei ohjaudu automaattisesti 10 sekunnin kuluessa,"
  "redirect_click_link" = "paina tästä"
  "return_to_your_charges" = "Palaa takaisin <a href=\"/cgi-bin/koha/opac-account.pl\">maksuihisi</a>."
  "transaction_not_found" = "Tilausta ei löytynyt."
  "unknown_error" = "Tuntematon virhe."
  "your_payment_breadcrumb" = "Maksusi"
  "your_payment_of" = "Maksusi "
}
%]
