[%
TOKENS = {
  "already_paid" = "Denna betalning har redan behandlats och betalats."
  "contact_librarian" = "Kontakta bibliotekspersonal för detaljer"
  "error_occurred" = "Något gick fel - betalningen kunde inte utföras"
  "error_occurred_contact_library" = ". Kontakta biblioteket."
  "home_breadcrumb" = "Hem"
  "no_amount" = "Det fanns inget belopp registrerat!"
  "order_id" = "Ordernummer"
  "payment_cancelled" = "Din betalning avbröts."
  "payment_process_success" = " är genomförd!"
  "payment_result_breadcrumb" = "Utförd betalning"
  "redirect" = "Du flyttas till Swedbank Pay..."
  "redirect_click_label" = "Om du inte flyttas inom 10 sekunder,"
  "redirect_click_link" = "klicka här"
  "return_to_your_charges" = "Återgå till vy för <a href=\"/cgi-bin/koha/opac-account.pl\">avgifter</a>."
  "transaction_not_found" = "Transaktionen kunde inte hittas."
  "unknown_error" = "Okänt fel."
  "your_payment_breadcrumb" = "Din betalning"
  "your_payment_of" = "Din betalning på "
}
%]
